name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov pylint
        
    - name: Lint with pylint
      run: |
        pylint app/ --disable=C0111,C0103
        
    - name: Test with pytest
      run: |
        pytest --cov=app tests/
        
    - name: Check coverage threshold
      run: |
        python -m pytest --cov=app --cov-report=term --cov-fail-under=90 tests/
        
    - name: Create coverage badge
      run: |
        pip install coverage-badge
        coverage-badge -o coverage.svg -f
        
    - name: Upload coverage badge
      uses: actions/upload-artifact@v3
      with:
        name: coverage-badge
        path: coverage.svg 